# Generated by Django 3.2 on 2024-02-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы категории для URL;разрешены символы латиницы,цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы жанра для URL;разрешены символы латиницы,цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор жанра'),
        ),
    ]
